### ISSUE TITLE
Add list of popular keywords.

### ISSUE THREAD

**Issue by kaeza** [cornernote/minetest-bower#15]
A "tag cloud" with keywords most used by mods would be nice (should be relatively trivial to implement).

Alternatively, define some "standard" tags for mods to use (e.g. "decoration", "system", etc.) and add a list of such categories.

**Comment by cornernote** [comment]
https://minetest-bower.herokuapp.com/cloud

enjoy!

**Comment by kaeza** [comment]
Perfect. Thank you!
Could they be made to appear in the main browser page along with the list?
