### ISSUE TITLE
support for webhooks

### ISSUE THREAD

**Issue by adrido** [cornernote/minetest-bower#21]
I'm not shure if github also supports something like webhooks, but bitbucket does:
https://confluence.atlassian.com/display/BITBUCKET/Manage+Webhooks

you can configure the webhook, that it automatical sends a http request to a specific webpage, every time a pull is made on git.
The bower can update the repo by itself, without pressing the update button.

**Comment by cornernote** [comment]
You can already do this.  I'll add some instructions below, and also add them to the page.

![Step 1](https://cloud.githubusercontent.com/assets/51875/9213427/6689597c-40d1-11e5-8f9c-5582e4d77dd2.png)
![Step 2](https://cloud.githubusercontent.com/assets/51875/9213433/7507bd2c-40d1-11e5-9a42-4f5e3a1da18e.png)
![Step 3](https://cloud.githubusercontent.com/assets/51875/9213435/7cf27a68-40d1-11e5-888a-c4692ad9f4b9.png)

**Comment by cornernote** [comment]
![Step 1](https://cloud.githubusercontent.com/assets/51875/9213650/39776c5a-40d4-11e5-82bc-3ca6fd81d7b5.png)
![Step 2](https://cloud.githubusercontent.com/assets/51875/9213652/3da76672-40d4-11e5-98d2-16c04f3c2fd2.png)

step3 pending... bitbucket seems to be broken, have sent support request

**Comment by adrido** [comment]
I know how to setup the webhook, and it works realy fine on other pages, but the bower page does not work:
![bitbucket org_2015-08-12_05-04-32](https://cloud.githubusercontent.com/assets/3142688/9215805/dd434306-40af-11e5-94d6-e4eb15da1f90.png)
Bitbucket only  gets a 400 HTTP error

**Comment by cornernote** [comment]
Interesting.  Thanks for pointing this out.  I'll check it out later tonight.

**Comment by cornernote** [comment]
The problem was CSRF validation was enabled please try again now.

**Comment by cornernote** [comment]
This image is being put here so I can put it on the site.

![BitBucket](https://cloud.githubusercontent.com/assets/51875/9217084/5f2da65c-4102-11e5-81b5-61b313a39aa7.png)

**Comment by adrido** [comment]
Works now, thanks 
![bitbucket org_2015-08-12_07-25-56](https://cloud.githubusercontent.com/assets/3142688/9217108/d7e49b08-40c3-11e5-8593-0ac66ad06e57.png)
