### ISSUE TITLE
wrong author information

### ISSUE THREAD

**Issue by adrido** [cornernote/minetest-bower#23]
just look at my [teleporter mod](https://minetest-bower.herokuapp.com/mods/teleporter) The webpage says author is "Bad_Command_" but author should be "kingarthursteam".

I know this issue can easily fixed by adding a bower.json file, but "Bad_Command_" sounds like a error message, so I think something is wrong there.

**Comment by cornernote** [comment]
the source data came from here:
https://github.com/rubenwardy/mtpm_lists/blob/gh-pages/lists/mods.csv#L170

i put in a pull request to change it here:
https://github.com/rubenwardy/mtpm_lists/pull/1/files

I also updated it on minetest-bower site.

**Comment by rubenwardy** [comment]
Both the author on the forum and github is "Bad Command" or similar. There is no mention of kingarthursteam on either pages. Having the repo author different from the forum and github usernames is confusing. Also, you are just a random GitHub user, not even from the same github account, how do we know you are who you say you are?

@Bad-Command

**Comment by rubenwardy** [comment]
Okay, I see what the problem is: there are two mods called teleporter, and the pull request was for the wrong one.

```
Bad_Command_, teleporter, https://github.com/Bad-Command/teleporter/, [Mod] Teleporter Mod [1.07] [teleporter], http://forum.minetest.net/viewtopic.php?f=11&t=2149
addi, teleporter, https://bitbucket.org/kingarthursteam/teleporter/, [Mod] Teleport Player and Items to other places [teleporter], http://forum.minetest.net/viewtopic.php?f=11&t=10620
```

There is nothing wrong with "Bad-Command", however it is weird how the rows got crossed like this (likely an error with cornernote's retriever, or maybe they both got changed to kingarthursteam).

**Comment by rubenwardy** [comment]
The Bad Command mod is older, so it arguably should get that mod name.

**Comment by Bad-Command** [comment]
Just thought I'd say Hi.  Hi!

I'm a real user, not an error message.  The nickname is supposed to be Bad_Command - underscores are not allowed on github, and someone stole "Bad_Command" on the forum.  I'm "Bad_Command_" there.

Nice idea with the teleporter destinations in a database, adrido/kingarthursteam.

Cheers.

**Comment by cornernote** [comment]
Hello,

If Bad_Command has the name first in the forums then he has the rights to the name on minetest-bower.

I have updated the mod accordingly.

@adrido, you may consider renaming your mod in order to have it listed in minetest-bower.  If you decide to do so please let me know, or submit the mod here:
http://minetest-bower.herokuapp.com/submit

**Comment by adrido** [comment]
Hi @Bad-Command 
Sorry, I hadn't noticed that Bad_Command_ is a user name. It sounds like a computer error to me :smile: 

@cornernote I dont think, that renaming is a good idea, because my mod also exists since a 3/4 Year and I does not know how much servers or users it already use.
Also if I rename my teleporter mod to teleporter+ teleporter++ or teleporter2 people may think my teleporter++ mod is better than Bad_Comand_'s teleporter mod.

I hope you can add a multiple modname feature like github or bitbucket do it: user/repo or author/mod e.g.  adrido/teleporter or Bad_Command_/teleporter.
This would be a great solution, because there exists some mods that have a lot of forks e.g. darkage.
So every user can have forks of existing mods without calling them *_plus or *_plus_plus witch would also break compatibility with the original mod.

**Comment by cornernote** [comment]
Hey @adrido,

You don't have to rename the mod on the forums or github, only on the minetest-bower site.  Unfortunately bower doesn't allow a username namespace in the mod name (no forward slash allowed).  The name `adrido_teleporter` would work.  Let me know if that's ok.

**Comment by adrido** [comment]
Yes, that's ok. Are there any problems then while installing the mod from the bower command line, because of renaming to correct modname?

**Comment by cornernote** [comment]
No there will be no issues reinstalling the mod unless there were already dependencies using it.  As it was new to bower, and bower itself is new then I suspect this would not be the case.  Should be all fine.

Mod is now listed here:
http://minetest-bower.herokuapp.com/mods/adrido_teleporter
