### ISSUE TITLE
"Error: ENOTFOUND" when I try install package mob-engine

### ISSUE THREAD

**Issue by diogogomes** [cornernote/minetest-bower#30]
When I try install package [mod-engine](https://minetest-bower.herokuapp.com/mod/view?name=mob-engine) with bower and I get this error:

> ENOTFOUND Package mob-engine not found

It's something wrong with your API? It's updated?

Thanks

**Comment by cornernote** [comment]
Hey @diogo-gomes, Thanks for pointing this out.  It was a bug in my Yii2 routing config.  Please try again now.
