### ISSUE TITLE
Show description.txt contents in mod page

### ISSUE THREAD

**Issue by Wuzzy2** [cornernote/minetest-bower#31]
Currently, the `description.txt` file is only shown on the mod page if there is no readme. I suggest to always show its contents, but in the small “infobox” at the right side (along name, keywords, links, etc.).

**Comment by cornernote** [comment]
It was there, but commented out.  Wonder why I wanted to hide it.  I think it may have been because the information was almost always duplicated in the readme.

Oh well, we'll display it now! :)
