### ISSUE TITLE
Duplicate mods: pipeworks and minetest-mods-pipeworks

### ISSUE THREAD

**Issue by diogogomes** [cornernote/minetest-bower#32]
I've detected same mod registed two times with diferent names:

- [pipeworks](https://minetest-bower.herokuapp.com/mods/pipeworks) (Deprecated)
- [minetest-mods-pipeworks](https://minetest-bower.herokuapp.com/mods/minetest-mods-pipeworks) (Wrong name)

I suggest delete both and then submit https://github.com/minetest-mods/pipeworks with name **pipeworks**.

**Comment by cornernote** [comment]
Thanks for pointing this out.  I deleted both and re-added https://minetest-bower.herokuapp.com/mods/pipeworks
