### ISSUE TITLE
Possible deprecated and duplicated mods: mesecons / minetest-mod-mesecons 

### ISSUE THREAD

**Issue by diogogomes** [cornernote/minetest-bower#34]
The mods [mesecons](https://minetest-bower.herokuapp.com/mods/mesecons) and [minetest-mod-mesecons](https://minetest-bower.herokuapp.com/mods/minetest-mod-mesecons) are duplicated and the link of project is [github.com/Jeija/minetest-mod-mesecons](https://github.com/Jeija/minetest-mod-mesecons) in both.
After click, the link redirects to [github.com/minetest-mods/mesecons](https://github.com/minetest-mods/mesecons)

I suggest delete both and submit the link **github.com/minetest-mods/mesecons** with same name **mesecons**.

**Comment by cornernote** [comment]
Thanks @diogo-gomes 

Done

```
DELETE FROM package WHERE name='mesecons';
DELETE FROM package WHERE name='minetest-mod-mesecons';
```

ADDED https://github.com/minetest-mods/mesecons.git as mesecons
