### ISSUE TITLE
Duplicate mods: digilines and minetest-mod-digilines

### ISSUE THREAD

**Issue by diogogomes** [cornernote/minetest-bower#35]
I've detected same mod with different names:

- [digilines](https://minetest-bower.herokuapp.com/mods/digilines)
- [minetest-mods-digilines](https://minetest-bower.herokuapp.com/mods/minetest-mod-digilines)

I suggest keep **digilines** and delete **minetest-mods-digilines**.

**Comment by cornernote** [comment]
Thanks @diogo-gomes 

Done

```
DELETE FROM package WHERE name='digilines';
DELETE FROM package WHERE name='minetest-mod-digilines';
```

ADDED https://github.com/minetest-mods/digilines.git as digilines
