### ISSUE TITLE
Deprecated mod: moreblocks

### ISSUE THREAD

**Issue by diogogomes** [cornernote/minetest-bower#36]
The mod [moreblocks](https://minetest-bower.herokuapp.com/mods/moreblocks) is deprecated.

The new link is [github.com/minetest-mods/moreblocks](https://github.com/minetest-mods/moreblocks)

I suggest delete and submit the new link with same name **moreblocks**.

**Comment by cornernote** [comment]
Thanks @diogo-gomes 

Done

```
DELETE FROM package WHERE name='moreblocks';
```

ADDED https://github.com/minetest-mods/moreblocks.git as moreblocks
