### ISSUE TITLE
Deprecated mod: mapfix

### ISSUE THREAD

**Issue by diogogomes** [cornernote/minetest-bower#37]
The mod [mapfix](https://minetest-bower.herokuapp.com/mods/mapfix) is deprecated.

The new link is [github.com/minetest-mods/mapfix](https://github.com/minetest-mods/mapfix)

I suggest to delete and submit the new link with same name **mapfix**.

**Comment by cornernote** [comment]
Thanks @diogo-gomes 

Done

```
DELETE FROM package WHERE name='mapfix';
```

ADDED https://github.com/minetest-mods/mapfix.git as mapfix
