### ISSUE TITLE
Deprecated mod: spidermob

### ISSUE THREAD

**Issue by diogogomes** [cornernote/minetest-bower#38]
The mod [spidermob](https://minetest-bower.herokuapp.com/mods/spidermob) is deprecated.

The new link is [github.com/darcidride/minetest-spidermob-v1](https://github.com/darcidride/minetest-spidermob-v1)

I suggest remove and submit the new link with same name **spidermob**.

**Comment by cornernote** [comment]
Thanks @diogo-gomes 

Done

```
DELETE FROM package WHERE name='mapfix';
```

ADDED github.com/darcidride/minetest-spidermob-v1 as spidermob

**Comment by cornernote** [comment]
Typo, meant

```
DELETE FROM package WHERE name='spidermob';
```
