### ISSUE TITLE
Accidental mod entry: show_item_names

### ISSUE THREAD

**Issue by Wuzzy2** [cornernote/minetest-bower#41]
Oops!
I accidentally added a mod under a wrong name. Please remove the following entry:
https://minetest-bower.herokuapp.com/mods/show_item_names

The correct entry has already been added:
https://minetest-bower.herokuapp.com/mods/show_wielded_item

**Comment by cornernote** [comment]
Do you want to be an admin on the heroku account?  It would mean you can
get access to the postgres DB and remove entries.

If so, shoot me an email to cornernote@gmail.com.


-- Brett

**Comment by Wuzzy2** [comment]
No. I just wanted to report my silly mistake. :-)

**Comment by cornernote** [comment]
done

```
minetest-bower::DATABASE=> DELETE FROM package WHERE name='show_item_names';
DELETE 1
```
